sql server desteği eklendi.
furkandeveloper/AuditSharp pull request #4
Opened 2024-12-21 18:28 UTC by mzuvin

Interceptor sınıfındaki hataları düzelttim. sql serverda update olduğu zaman eski değerleri mevcut kodda yazmıyordu. servis isimlerinin sonunda ilgili db'nin ismini ekledim karışmasın diye.  örnek bir web proje ekledim. DesignTimeDbContext için de dinamik appsettings kodu ekledim. eksik olarak auditlog sınıfı partial yapılabilir ve userid eklenip o an değişikliğin kimin yapıldığı eklenebilir.

2024-12-22 11:25 UTC, furkandeveloper commented
Harika görünüyor. Oldukça fazla değişiklik var. Hepsini kontrol etmek biraz zamanımı alabilir. Katkın için teşekkür ederim. En kısa zamanda ilgileneceğim. 🚀 @mzuvin

2024-12-29 13:59 UTC, furkandeveloper commented on src/AuditSharp.SqlServer/Extensions/IoCManager.cs
> +namespace AuditSharp.PostgreSql.Extensions;
Wrong namespace

2024-12-29 14:01 UTC, furkandeveloper commented on src/AuditSharp.SqlServer/Extensions/IoCManager.cs
> +namespace AuditSharp.PostgreSql.Extensions;
@mzuvin

2024-12-29 14:02 UTC, furkandeveloper requested changes
- Yanlış bir namespace tanımı var.
- Mevcut kütüphane üzerinde değişiklik olduğu için doc güncellenmeli.
- SQL server için how_to_use dökümanı yazılmalı.

2024-12-29 14:22 UTC, mzuvin commented on src/AuditSharp.SqlServer/Extensions/IoCManager.cs
> +namespace AuditSharp.PostgreSql.Extensions;
düzelttim

2024-12-29 15:19 UTC, mzuvin commented
> * Yanlış bir namespace tanımı var. **fix.**
> * Mevcut kütüphane üzerinde değişiklik yapılmamalı. Diğer PR'lar da olduğu gibi mevcut yapı örnek alınıyor. SQL Server içindeki tanımlamalar postgre üzerindeki gibi olmalı. **fix.**
> * SQL server için how_to_use dökümanı yazılmalı. **mevcut dökümana eklendi.**

2025-11-09 09:58 UTC, closed without merging